--- 
title: "Evaluation of Environmental Justice Criteria"
author: "Marcos Luna, PhD, Professor of Geography, Salem State University"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: "This is an analysis of the criteria for defining Environmental Justice communities in Massachusetts."
---

# Summary {-}

This document presents an analysis of the demographic criteria used to identify Environmental Justice communities in Massachusetts. Specifically, it uses the Massachusetts Environmental Justice policies in place since 2010 as benchmarks of comparison to assess the impacts of adjustments in several  criteria: percent minority, and income and educational constraints. This analysis was motivated by an interest in improving the the policy for identifying Environmental Justice communities, such that vulnerable communities are approporiately identified, while minimizing the inappropriate classification of less vulnerable communities as Environmental Justice communities. Environmental Justice is an important goal of the Commonwealth, and it behooves policy makers to maintain the policy's legitimacy by ensuring that it works to the benefit of communities that are truly vulnerable or which have been targeted or neglected. 

In general, the analysis finds that adding income constraints to the criteria for minority and English language isolation results in the most efficient reduction of inappropriately classified Environmental Justice communities, while also maintaining classification for communities that are clearly vulnerable or that have historically struggled with environmental discrimination or neglect by the state and society at large. 

Details of the analysis, including graphs, tables, and interactive maps are presented below.